[DYSON_ACCOUNT]
email = smart.energy.platform@gmail.com
pw = connector1!
country = DE

[DYSON_API]
url = api.cp.dyson.com
user = 
pw = 

[SEPL]
device_type = iot#76523381-1b19-4280-9028-c3fa30899996
device_service_humidity = humidity_reading
device_service_volatile = volatile_comp_reading
device_service_temperature = temperature_reading
device_service_dust = dust_reading

